### PR TITLE
#25 Default bundle not showing

### PR DESCRIPTION
**Pull request by LZaruba**
Changed behavior of fragment vs. host plugin resulting files merging to
prefer fragment files over the host files but if there is no file for
the given locale in fragment, host file is loaded.
This fixes the bug as it no longer checks and skip for null locale (=
default)

### CODE REVIEW

**Comment by k0ner** [comment]
I assume that this change resolves problems with Eclipse Luna - what with other versions? Have you checked older & the newest version? Is everything fine after your change?

**Comment by LZaruba** [comment]
Hi,
it is verified against Mars.1 Release (4.5.1) on Mac (10.11.1)
I believe that the nature of the fix is not version nor platform dependent
as it was in the null check.
Can you verify it with Luna?

Cheers

LZ

On Tue, Nov 3, 2015 at 10:32 PM, k0ner <notifications@github.com> wrote:

> I assume that this change resolves problems with Eclipse Luna - what with
> other versions? Have you checked older & the newest version? Is everything
> fine after your change?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/essiembre/eclipse-rbe/pull/41#issuecomment-153496149>.
>



-- 
Lukáš Záruba

**Comment by LZaruba** [comment]
Hi,
can you please contact me on email (you can find it in my profile) so we can coordinate on the project as I was recently appointed a Collaborator.
Thanks
LZ

**Comment by LZaruba** [comment]
Both fixes for #25 and #27 were merged into develop branch manually

**Pull request closed without merging**
